FIX

diff --git a/build b/build
--- a/build
+++ b/build
@@ -8,16 +8,36 @@ export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
 export USE_GAPPS=true
-ccache -M 30G # It took only 6.4GB for mido
-ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
-ccache -z # Clear old stats, so monitor script will provide real ccache statistics
-
-# Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines Sepolicy Fix.
-make sepolicy
-make init
-make bootimage
-mka nad & # dont remove that '&'
-sleep 30m
-kill %1
+ccache -M 20G
+ccache -o compression=true
+ccache -z
 ccache -s
-and dont use below codes for first 1 or 2 times, to get ccache uploaded,
+
+# metalava
+make_metalava(){
+	make sepolicy
+	make init
+	make booimage
+}
+
+make_metalava
+mka nad
+#sleep 75m
+#kill %1 || echo "Build already failed or completed"
+ccache -s
+
+# upload
+
+up(){
+	curl --upload-file $1 https://transfer.sh/$(basename$1); echo
+	# 14 days, 10 GB limit
+}
+
+
+#up(){
+#	time rclone copy $1 aosp:ccache/ccache-ci -P # apon is my rclone config name, 
+#}
+
+up out/target/product/RMX1941/*UNOFFICIAL*.zip || echo "Only ccache generated or build failed lol"
+
+ccache -s
